apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  template:
    spec:
      containers:
        - name: app
          image: app
          imagePullPolicy: IfNotPresent
      initContainers:
        - name: sidecar
          image: sidecar
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
      restartPolicy: Never

